Custom Edit Actions
readium/r2-navigator-swift pull request #181
Opened 2021-06-10 15:08 UTC by cbaltzer

Allows for adding new actions to the selection menu.

The `EditingAction` enum has be converted to a struct, and the existing cases as static values. This should _hopefully_ not break compatibility.

New actions can be created like so:

```
        var config = EPUBNavigatorViewController.Configuration.init()

        let actions = [
            EditingAction(rawValue: "highlight:", name: "Highlight")
        ]
        config.editingActions = actions

        self.navigator = EPUBNavigatorViewController(publication: publication,
                                                     initialLocation: nil,
                                                     resourcesServer: ReaderService.shared.server,
                                                     config: config)
```

The action's implementation can be added as an extension on `WKWebView`:

```
extension WKWebView {
    @objc func highlight(_ sender: UIMenuItem) {
        print("Highlighting some text")
    }
}
```

2021-06-11 13:14 UTC, mickael-menu requested changes
I'm not a fan of the term "editing action" which is a bit confusing IMHO in the selection context, since there's no actual editing being done. So I wouldn't conflate the existing "editing actions" and the new menu items.

Maybe we can keep the editing actions (i.e. native menu items) as-is but add a new struct only for the custom menu items. This would also make the target more explicit than your example extending `WKWebView`. For example:


```swift
public struct MenuItem {
    public let title: String
    
    public init(title: String, target: Any, action: Selector) {
        self.title = title
        self.action = .targetAction(TargetAction(target: target, action: action)))
    }

    public init(title: String, block: @escaping (Any?) -> Void) {
        self.title = title
        self.action = .block(block)
    }

    public invoke(from sender: Any? = nil) {
        switch action {
            case .block(let block):
                block(sender)
            case .targetAction(let targetAction):
                targetAction.invoke(from: sender)
        }
    }

    private let action: Action
    private enum Action {
        case targetAction(TargetAction)
        case block((Any?) -> Void)
    }
}
```

To be used like this:

```swift
        var config = EPUBNavigatorViewController.Configuration()
        // Still available for native actions.
        config.editingActions = [.copy]

        config.selectionMenuItems = [
            MenuItem(title: "Highlight", target: self, action: #selector(highlight:)),
            MenuItem(title: "Annotate") { sender in
                ...
            }
        ]
```

What do you think?

With the 3.0 we will probably unify a bit the Selection API and deprecate "editing actions".

2021-06-11 16:14 UTC, cbaltzer commented on r2-navigator-swift/EditingAction.swift
> +public final class EditingActionsController {
Ah, missed that. I thought the selectors would need to be added here instead of the `WKWebView`.

2021-06-21 12:14 UTC, mickael-menu commented
@cbaltzer Do you plan to follow-up on this PR? It is quite promising.

2021-07-06 09:53 UTC, mickael-menu approved these changes
@cbaltzer I've reworked your PR and now I see where your implementation was coming from. With `UIMenuController`, there's no way to provide a closure or even (easily) a custom target/selector pair.

So let's embrace the editing actions system of `UIMenuController`. I just fixed a bit your PR to simplify the usage in reading apps. Now you must provide a valid selector for safety, and it just needs to be implemented in any class of the responder chain, most likely the wrapping `UIViewController`, for example:

```swift
class EPUBViewController: UIViewController {
    init(publication: Publication) {
        let navigator = EPUBNavigatorViewController(
            publication: publication,
            config: EPUBNavigatorViewController.Configuration(
                editingActions: [
                    .copy,
                    .share,
                    EditingAction(title: "Highlight", action: #selector(highlight))
                ]
            ))
    }

    @objc func highlight(_ sender: Any) {
        print("Highlighting")
    }
}
```

(Or nicer IMHO)

```swift
extension EditingAction {
    static let highlight = EditingAction(title: "Highlight", action: #selector(BaseReaderViewController.highlight))
}

editingActions: [.copy, .share, .highlight]
```
Next I'll be working on a `SelectableNavigator` protocol to get the information about the current selection, and optionally fully override the `UIMenuController` to be able to provide a custom selection popup.

2021-07-06 09:55 UTC, merged